# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Patricia\Economystique2\account.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_account(object):
    def setupUi(self, account):
        account.setObjectName("account")
        account.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/econoLogo2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        account.setWindowIcon(icon)
        account.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;\n"
"")
        self.lblRole = QtWidgets.QLabel(account)
        self.lblRole.setGeometry(QtCore.QRect(510, 300, 211, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblRole.setFont(font)
        self.lblRole.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRole.setObjectName("lblRole")
        self.lblUserName = QtWidgets.QLabel(account)
        self.lblUserName.setGeometry(QtCore.QRect(460, 260, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.lblUserName.setFont(font)
        self.lblUserName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserName.setObjectName("lblUserName")
        self.btnLogOut = QtWidgets.QPushButton(account)
        self.btnLogOut.setGeometry(QtCore.QRect(350, 520, 93, 28))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.btnLogOut.setFont(font)
        self.btnLogOut.setStyleSheet("color: white;\n"
"background-color: red;\n"
"\n"
"")
        self.btnLogOut.setFlat(False)
        self.btnLogOut.setObjectName("btnLogOut")
        self.frame_2 = QtWidgets.QFrame(account)
        self.frame_2.setGeometry(QtCore.QRect(60, 320, 271, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lblBsnsType = QtWidgets.QLabel(self.frame_2)
        self.lblBsnsType.setGeometry(QtCore.QRect(0, 0, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblBsnsType.setFont(font)
        self.lblBsnsType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBsnsType.setObjectName("lblBsnsType")
        self.lblOwnership = QtWidgets.QLabel(self.frame_2)
        self.lblOwnership.setGeometry(QtCore.QRect(0, 30, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblOwnership.setFont(font)
        self.lblOwnership.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOwnership.setObjectName("lblOwnership")
        self.lblLocation = QtWidgets.QLabel(self.frame_2)
        self.lblLocation.setGeometry(QtCore.QRect(0, 60, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblLocation.setFont(font)
        self.lblLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLocation.setObjectName("lblLocation")
        self.lblBusinessName_2 = QtWidgets.QLabel(account)
        self.lblBusinessName_2.setGeometry(QtCore.QRect(290, 70, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(18)
        self.lblBusinessName_2.setFont(font)
        self.lblBusinessName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBusinessName_2.setObjectName("lblBusinessName_2")
        self.frame = QtWidgets.QFrame(account)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.titleLabel_2 = QtWidgets.QLabel(self.frame)
        self.titleLabel_2.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.titleLabel_2.setFont(font)
        self.titleLabel_2.setStyleSheet("color: white;")
        self.titleLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_2.setObjectName("titleLabel_2")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(570, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(480, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(660, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(750, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/pfBtn.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.imgProfile = QtWidgets.QLabel(account)
        self.imgProfile.setGeometry(QtCore.QRect(570, 160, 101, 91))
        self.imgProfile.setText("")
        self.imgProfile.setPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/profile.png"))
        self.imgProfile.setScaledContents(True)
        self.imgProfile.setObjectName("imgProfile")
        self.imgBusinessLogo = QtWidgets.QLabel(account)
        self.imgBusinessLogo.setGeometry(QtCore.QRect(130, 160, 101, 101))
        self.imgBusinessLogo.setText("")
        self.imgBusinessLogo.setPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/allseasonsL.jpg"))
        self.imgBusinessLogo.setScaledContents(True)
        self.imgBusinessLogo.setObjectName("imgBusinessLogo")
        self.lblBusinessName = QtWidgets.QLabel(account)
        self.lblBusinessName.setGeometry(QtCore.QRect(50, 270, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.lblBusinessName.setFont(font)
        self.lblBusinessName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBusinessName.setObjectName("lblBusinessName")

        self.retranslateUi(account)
        QtCore.QMetaObject.connectSlotsByName(account)

    def retranslateUi(self, account):
        _translate = QtCore.QCoreApplication.translate
        account.setWindowTitle(_translate("account", "EconoMystique"))
        self.lblRole.setText(_translate("account", "Owner"))
        self.lblUserName.setText(_translate("account", "Kathlyn O. Lascota"))
        self.btnLogOut.setText(_translate("account", "Log Out"))
        self.lblBsnsType.setText(_translate("account", "Business Type:"))
        self.lblOwnership.setText(_translate("account", "Ownership:"))
        self.lblLocation.setText(_translate("account", "Location:"))
        self.lblBusinessName_2.setText(_translate("account", "Account"))
        self.titleLabel_2.setText(_translate("account", "EconoMystique"))
        self.btnSales.setText(_translate("account", "Sales"))
        self.btnInventory.setText(_translate("account", "Inventory"))
        self.btnPOS.setText(_translate("account", "POS"))
        self.lblBusinessName.setText(_translate("account", "All Seasons Cake Shop"))
