# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Patricia\Economystique2\account.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_account(object):
    def setupUi(self, account):
        account.setObjectName("account")
        account.resize(802, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/econologo_bkgd.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        account.setWindowIcon(icon)
        account.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;\n"
"")
        self.centralwidget = QtWidgets.QWidget(account)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.titleLabel_2 = QtWidgets.QLabel(self.frame)
        self.titleLabel_2.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.titleLabel_2.setFont(font)
        self.titleLabel_2.setStyleSheet("color: white;")
        self.titleLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel_2.setObjectName("titleLabel_2")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(570, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(480, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnCalendar = QtWidgets.QPushButton(self.frame)
        self.btnCalendar.setGeometry(QtCore.QRect(660, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCalendar.setFont(font)
        self.btnCalendar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalendar.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnCalendar.setObjectName("btnCalendar")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(750, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/pfBtn.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.imgBusinessLogo = QtWidgets.QLabel(self.centralwidget)
        self.imgBusinessLogo.setGeometry(QtCore.QRect(140, 100, 101, 101))
        self.imgBusinessLogo.setText("")
        self.imgBusinessLogo.setPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/allseasonsL.jpg"))
        self.imgBusinessLogo.setScaledContents(True)
        self.imgBusinessLogo.setObjectName("imgBusinessLogo")
        self.lblUserName = QtWidgets.QLabel(self.centralwidget)
        self.lblUserName.setGeometry(QtCore.QRect(470, 200, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.lblUserName.setFont(font)
        self.lblUserName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserName.setObjectName("lblUserName")
        self.lblBusinessName = QtWidgets.QLabel(self.centralwidget)
        self.lblBusinessName.setGeometry(QtCore.QRect(60, 210, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        self.lblBusinessName.setFont(font)
        self.lblBusinessName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBusinessName.setObjectName("lblBusinessName")
        self.btnEditProfile = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditProfile.setGeometry(QtCore.QRect(730, 330, 41, 31))
        self.btnEditProfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEditProfile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/editPfp.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnEditProfile.setIcon(icon2)
        self.btnEditProfile.setFlat(True)
        self.btnEditProfile.setObjectName("btnEditProfile")
        self.btnLogOut = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogOut.setGeometry(QtCore.QRect(360, 540, 93, 28))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.btnLogOut.setFont(font)
        self.btnLogOut.setStyleSheet("color: white;\n"
"background-color: red;\n"
"\n"
"")
        self.btnLogOut.setFlat(False)
        self.btnLogOut.setObjectName("btnLogOut")
        self.lblFSTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblFSTitle.setGeometry(QtCore.QRect(350, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblFSTitle.setFont(font)
        self.lblFSTitle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblFSTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFSTitle.setObjectName("lblFSTitle")
        self.imgProfile = QtWidgets.QLabel(self.centralwidget)
        self.imgProfile.setGeometry(QtCore.QRect(580, 100, 101, 91))
        self.imgProfile.setText("")
        self.imgProfile.setPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/profile.png"))
        self.imgProfile.setScaledContents(True)
        self.imgProfile.setObjectName("imgProfile")
        self.lblBusinessName_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblBusinessName_2.setGeometry(QtCore.QRect(310, 60, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(18)
        self.lblBusinessName_2.setFont(font)
        self.lblBusinessName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBusinessName_2.setObjectName("lblBusinessName_2")
        self.lblRole = QtWidgets.QLabel(self.centralwidget)
        self.lblRole.setGeometry(QtCore.QRect(520, 240, 211, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblRole.setFont(font)
        self.lblRole.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRole.setObjectName("lblRole")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(70, 260, 271, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lblBsnsType = QtWidgets.QLabel(self.frame_2)
        self.lblBsnsType.setGeometry(QtCore.QRect(0, 0, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblBsnsType.setFont(font)
        self.lblBsnsType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBsnsType.setObjectName("lblBsnsType")
        self.lblOwnership = QtWidgets.QLabel(self.frame_2)
        self.lblOwnership.setGeometry(QtCore.QRect(0, 30, 91, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblOwnership.setFont(font)
        self.lblOwnership.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOwnership.setObjectName("lblOwnership")
        self.lblLocation = QtWidgets.QLabel(self.frame_2)
        self.lblLocation.setGeometry(QtCore.QRect(0, 60, 111, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblLocation.setFont(font)
        self.lblLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLocation.setObjectName("lblLocation")
        self.fileListView = QtWidgets.QListView(self.centralwidget)
        self.fileListView.setGeometry(QtCore.QRect(20, 400, 761, 71))
        self.fileListView.setObjectName("fileListView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(630, 480, 151, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOpenFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnOpenFile.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnOpenFile.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/fileIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenFile.setIcon(icon3)
        self.btnOpenFile.setFlat(True)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.horizontalLayout.addWidget(self.btnOpenFile)
        self.btnDeleteFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnDeleteFile.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnDeleteFile.setAutoFillBackground(False)
        self.btnDeleteFile.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/deleteIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteFile.setIcon(icon4)
        self.btnDeleteFile.setFlat(True)
        self.btnDeleteFile.setObjectName("btnDeleteFile")
        self.horizontalLayout.addWidget(self.btnDeleteFile)
        self.btnAddFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddFile.setFont(font)
        self.btnAddFile.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnAddFile.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/addIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddFile.setIcon(icon5)
        self.btnAddFile.setFlat(True)
        self.btnAddFile.setObjectName("btnAddFile")
        self.horizontalLayout.addWidget(self.btnAddFile)
        account.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(account)
        self.statusbar.setObjectName("statusbar")
        account.setStatusBar(self.statusbar)

        self.retranslateUi(account)
        QtCore.QMetaObject.connectSlotsByName(account)

    def retranslateUi(self, account):
        _translate = QtCore.QCoreApplication.translate
        account.setWindowTitle(_translate("account", "Economystique"))
        self.titleLabel_2.setText(_translate("account", "EconoMystique"))
        self.btnSales.setText(_translate("account", "Sales"))
        self.btnInventory.setText(_translate("account", "Inventory"))
        self.btnCalendar.setText(_translate("account", "Calendar"))
        self.lblUserName.setText(_translate("account", "Kathlyn O. LAscota"))
        self.lblBusinessName.setText(_translate("account", "All Seasons Cake Shop"))
        self.btnLogOut.setText(_translate("account", "Log Out"))
        self.lblFSTitle.setText(_translate("account", "Existing Files"))
        self.lblBusinessName_2.setText(_translate("account", "Account"))
        self.lblRole.setText(_translate("account", "Owner"))
        self.lblBsnsType.setText(_translate("account", "Business Type:"))
        self.lblOwnership.setText(_translate("account", "Ownership:"))
        self.lblLocation.setText(_translate("account", "Location:"))
