# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\addExisting.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddExisting(object):
    def setupUi(self, AddExisting):
        AddExisting.setObjectName("AddExisting")
        AddExisting.resize(400, 183)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddExisting.setWindowIcon(icon)
        AddExisting.setStyleSheet("background-color: #f4f4ec;")
        self.buttonBox = QtWidgets.QDialogButtonBox(AddExisting)
        self.buttonBox.setGeometry(QtCore.QRect(30, 140, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(AddExisting)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 81, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.teAmount = QtWidgets.QTextEdit(AddExisting)
        self.teAmount.setGeometry(QtCore.QRect(100, 80, 171, 31))
        self.teAmount.setStyleSheet("background: #ffffff")
        self.teAmount.setFrameShape(QtWidgets.QFrame.Panel)
        self.teAmount.setTabChangesFocus(True)
        self.teAmount.setObjectName("teAmount")
        self.cbItems = QtWidgets.QComboBox(AddExisting)
        self.cbItems.setGeometry(QtCore.QRect(102, 31, 281, 31))
        self.cbItems.setStyleSheet("background: white;")
        self.cbItems.setObjectName("cbItems")
        self.lblUnit = QtWidgets.QLabel(AddExisting)
        self.lblUnit.setGeometry(QtCore.QRect(284, 75, 101, 41))
        self.lblUnit.setText("")
        self.lblUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUnit.setObjectName("lblUnit")

        self.retranslateUi(AddExisting)
        self.buttonBox.accepted.connect(AddExisting.accept) # type: ignore
        self.buttonBox.rejected.connect(AddExisting.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddExisting)

    def retranslateUi(self, AddExisting):
        _translate = QtCore.QCoreApplication.translate
        AddExisting.setWindowTitle(_translate("AddExisting", "Add Exisiting Item"))
        self.label.setText(_translate("AddExisting", "Inventory ID"))
        self.label_2.setText(_translate("AddExisting", "Amount"))
        self.teAmount.setHtml(_translate("AddExisting", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
