# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\addPrNew.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addPrNew(object):
    def setupUi(self, addPrNew):
        addPrNew.setObjectName("addPrNew")
        addPrNew.resize(802, 364)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addPrNew.setWindowIcon(icon)
        addPrNew.setStyleSheet("background-color: #f4f4ec;")
        self.btnRemove = QtWidgets.QPushButton(addPrNew)
        self.btnRemove.setGeometry(QtCore.QRect(550, 240, 111, 31))
        self.btnRemove.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnRemove.setObjectName("btnRemove")
        self.btnCancel = QtWidgets.QPushButton(addPrNew)
        self.btnCancel.setGeometry(QtCore.QRect(410, 310, 121, 31))
        self.btnCancel.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.btnConfirm = QtWidgets.QPushButton(addPrNew)
        self.btnConfirm.setGeometry(QtCore.QRect(260, 310, 121, 31))
        self.btnConfirm.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnAdd = QtWidgets.QPushButton(addPrNew)
        self.btnAdd.setGeometry(QtCore.QRect(140, 240, 121, 31))
        self.btnAdd.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAdd.setObjectName("btnAdd")
        self.tabRestockTable = QtWidgets.QTableWidget(addPrNew)
        self.tabRestockTable.setGeometry(QtCore.QRect(400, 30, 391, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabRestockTable.sizePolicy().hasHeightForWidth())
        self.tabRestockTable.setSizePolicy(sizePolicy)
        self.tabRestockTable.setMaximumSize(QtCore.QSize(771, 351))
        self.tabRestockTable.setStyleSheet("background: #ffffff")
        self.tabRestockTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabRestockTable.setObjectName("tabRestockTable")
        self.tabRestockTable.setColumnCount(0)
        self.tabRestockTable.setRowCount(0)
        self.teInvID = QtWidgets.QTextEdit(addPrNew)
        self.teInvID.setGeometry(QtCore.QRect(130, 30, 261, 31))
        self.teInvID.setStyleSheet("background: #ffffff")
        self.teInvID.setFrameShape(QtWidgets.QFrame.Panel)
        self.teInvID.setTabChangesFocus(True)
        self.teInvID.setObjectName("teInvID")
        self.teInvID_2 = QtWidgets.QTextEdit(addPrNew)
        self.teInvID_2.setGeometry(QtCore.QRect(130, 70, 261, 31))
        self.teInvID_2.setStyleSheet("background: #ffffff")
        self.teInvID_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.teInvID_2.setTabChangesFocus(True)
        self.teInvID_2.setObjectName("teInvID_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(addPrNew)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 29, 111, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(addPrNew)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 111, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(addPrNew)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.teInvID_3 = QtWidgets.QTextEdit(addPrNew)
        self.teInvID_3.setGeometry(QtCore.QRect(130, 200, 261, 31))
        self.teInvID_3.setStyleSheet("background: #ffffff")
        self.teInvID_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.teInvID_3.setTabChangesFocus(True)
        self.teInvID_3.setObjectName("teInvID_3")
        self.cbItems = QtWidgets.QComboBox(addPrNew)
        self.cbItems.setGeometry(QtCore.QRect(130, 160, 261, 31))
        self.cbItems.setStyleSheet("background: white;")
        self.cbItems.setObjectName("cbItems")

        self.retranslateUi(addPrNew)
        QtCore.QMetaObject.connectSlotsByName(addPrNew)

    def retranslateUi(self, addPrNew):
        _translate = QtCore.QCoreApplication.translate
        addPrNew.setWindowTitle(_translate("addPrNew", "New Product"))
        self.btnRemove.setText(_translate("addPrNew", "Remove"))
        self.btnCancel.setText(_translate("addPrNew", "❌Cancel"))
        self.btnConfirm.setText(_translate("addPrNew", "✔️ Confirm"))
        self.btnAdd.setText(_translate("addPrNew", "Add"))
        self.teInvID.setHtml(_translate("addPrNew", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teInvID_2.setHtml(_translate("addPrNew", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_11.setText(_translate("addPrNew", "Product ID"))
        self.label_12.setText(_translate("addPrNew", "Product Name"))
        self.label_14.setText(_translate("addPrNew", "Ingredient"))
        self.label_15.setText(_translate("addPrNew", "Amount"))
        self.label_16.setText(_translate("addPrNew", "Add Ingredient"))
        self.teInvID_3.setHtml(_translate("addPrNew", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
