# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\comparison.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Comparison(object):
    def setupUi(self, Comparison):
        Comparison.setObjectName("Comparison")
        Comparison.resize(1600, 900)
        self.frame = QtWidgets.QFrame(Comparison)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1601, 61))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(1312, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(1202, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(1422, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(1530, 0, 71, 61))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnAccount.setIcon(icon)
        self.btnAccount.setIconSize(QtCore.QSize(50, 50))
        self.btnAccount.setObjectName("btnAccount")
        self.btnDashboard = QtWidgets.QPushButton(self.frame)
        self.btnDashboard.setGeometry(QtCore.QRect(0, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon1)
        self.btnDashboard.setIconSize(QtCore.QSize(30, 30))
        self.btnDashboard.setObjectName("btnDashboard")
        self.label_2 = QtWidgets.QLabel(Comparison)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 1581, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: black;")
        self.label_2.setLineWidth(1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gpPerformance = QtWidgets.QWidget(Comparison)
        self.gpPerformance.setGeometry(QtCore.QRect(20, 270, 1261, 611))
        self.gpPerformance.setStyleSheet("QWidget {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background-color: #f4f4ec;\n"
"    padding: 0px;\n"
"}")
        self.gpPerformance.setObjectName("gpPerformance")
        self.cbMonth = QtWidgets.QComboBox(Comparison)
        self.cbMonth.setGeometry(QtCore.QRect(150, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbMonth.setFont(font)
        self.cbMonth.setStyleSheet("background: white;")
        self.cbMonth.setObjectName("cbMonth")
        self.label_7 = QtWidgets.QLabel(Comparison)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(Comparison)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cbYear = QtWidgets.QComboBox(Comparison)
        self.cbYear.setGeometry(QtCore.QRect(150, 220, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbYear.setFont(font)
        self.cbYear.setStyleSheet("background: white;")
        self.cbYear.setObjectName("cbYear")
        self.btnAdd = QtWidgets.QPushButton(Comparison)
        self.btnAdd.setGeometry(QtCore.QRect(410, 180, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnAdd.setFont(font)
        self.btnAdd.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAdd.setObjectName("btnAdd")
        self.btnClrGraph = QtWidgets.QPushButton(Comparison)
        self.btnClrGraph.setGeometry(QtCore.QRect(1330, 800, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnClrGraph.setFont(font)
        self.btnClrGraph.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnClrGraph.setObjectName("btnClrGraph")
        self.lsGraphs = QtWidgets.QListView(Comparison)
        self.lsGraphs.setGeometry(QtCore.QRect(1300, 270, 281, 511))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.lsGraphs.setFont(font)
        self.lsGraphs.setStyleSheet("#lsGraphs {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background-color: #f4f4ec;\n"
"    padding: 3px;\n"
"}")
        self.lsGraphs.setObjectName("lsGraphs")

        self.retranslateUi(Comparison)
        QtCore.QMetaObject.connectSlotsByName(Comparison)

    def retranslateUi(self, Comparison):
        _translate = QtCore.QCoreApplication.translate
        Comparison.setWindowTitle(_translate("Comparison", "Compare Perofrmance"))
        self.btnSales.setText(_translate("Comparison", "Sales"))
        self.btnInventory.setText(_translate("Comparison", "Inventory"))
        self.btnPOS.setText(_translate("Comparison", "POS"))
        self.btnDashboard.setText(_translate("Comparison", "EconoMystique"))
        self.label_2.setText(_translate("Comparison", "Compare Performance"))
        self.label_7.setText(_translate("Comparison", "Year:"))
        self.label_3.setText(_translate("Comparison", "Month:"))
        self.btnAdd.setText(_translate("Comparison", "Add to Graph"))
        self.btnClrGraph.setText(_translate("Comparison", "Clear Graph"))
