# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(799, 600)
        Dashboard.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;\n"
"")
        self.frame = QtWidgets.QFrame(Dashboard)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(660, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(750, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccount.setIcon(icon)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(570, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(480, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnDashboard = QtWidgets.QPushButton(self.frame)
        self.btnDashboard.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon1)
        self.btnDashboard.setObjectName("btnDashboard")
        self.gpPerformance = QtWidgets.QWidget(Dashboard)
        self.gpPerformance.setGeometry(QtCore.QRect(10, 160, 501, 431))
        self.gpPerformance.setStyleSheet("background: white;")
        self.gpPerformance.setObjectName("gpPerformance")
        self.lsCritical = QtWidgets.QListWidget(Dashboard)
        self.lsCritical.setGeometry(QtCore.QRect(530, 161, 261, 421))
        self.lsCritical.setStyleSheet("Background: white;")
        self.lsCritical.setObjectName("lsCritical")
        self.label = QtWidgets.QLabel(Dashboard)
        self.label.setGeometry(QtCore.QRect(534, 125, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dashboard)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 781, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dashboard)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Form"))
        self.btnPOS.setText(_translate("Dashboard", "POS"))
        self.btnSales.setText(_translate("Dashboard", "Sales"))
        self.btnInventory.setText(_translate("Dashboard", "Inventory"))
        self.btnDashboard.setText(_translate("Dashboard", "EconoMystique"))
        self.label.setText(_translate("Dashboard", "Critical Items"))
        self.label_2.setText(_translate("Dashboard", "Dashboard"))
        self.label_3.setText(_translate("Dashboard", "This Month\'s Performance"))
