# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(1600, 900)
        Dashboard.setStyleSheet("color: black;")
        self.gpPerformance = QtWidgets.QWidget(Dashboard)
        self.gpPerformance.setGeometry(QtCore.QRect(20, 190, 1211, 541))
        self.gpPerformance.setStyleSheet("QWidget {\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    background-color: transparent;\n"
"    padding: 0px;\n"
"}")
        self.gpPerformance.setObjectName("gpPerformance")
        self.label_2 = QtWidgets.QLabel(Dashboard)
        self.label_2.setGeometry(QtCore.QRect(650, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px solid white;\n"
"background: #365b6d;\n"
"color: white;\n"
"border-radius: 25px;")
        self.label_2.setLineWidth(1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dashboard)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 1211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(Dashboard)
        self.frame_2.setGeometry(QtCore.QRect(1250, 190, 331, 541))
        self.frame_2.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background: rgba(0,0,0,128);\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lblBestProduct = QtWidgets.QLabel(self.frame_2)
        self.lblBestProduct.setGeometry(QtCore.QRect(10, 80, 311, 441))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblBestProduct.setFont(font)
        self.lblBestProduct.setStyleSheet("background: transparent;\n"
"color: white;")
        self.lblBestProduct.setText("")
        self.lblBestProduct.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBestProduct.setWordWrap(True)
        self.lblBestProduct.setObjectName("lblBestProduct")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(Dashboard)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1601, 61))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(1250, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(1140, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(1360, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(1468, 0, 71, 61))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnAccount.setIcon(icon)
        self.btnAccount.setIconSize(QtCore.QSize(50, 50))
        self.btnAccount.setObjectName("btnAccount")
        self.btnDashboard = QtWidgets.QPushButton(self.frame)
        self.btnDashboard.setGeometry(QtCore.QRect(0, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon1)
        self.btnDashboard.setIconSize(QtCore.QSize(30, 30))
        self.btnDashboard.setObjectName("btnDashboard")
        self.btnNotif = QtWidgets.QPushButton(self.frame)
        self.btnNotif.setGeometry(QtCore.QRect(1540, 0, 61, 61))
        self.btnNotif.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}")
        self.btnNotif.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/notif.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNotif.setIcon(icon2)
        self.btnNotif.setIconSize(QtCore.QSize(40, 40))
        self.btnNotif.setObjectName("btnNotif")
        self.lblBadge = QtWidgets.QLabel(self.frame)
        self.lblBadge.setGeometry(QtCore.QRect(1570, 30, 21, 21))
        self.lblBadge.setStyleSheet("color: white;\n"
"background-color: red;\n"
"border-radius: 10px;")
        self.lblBadge.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBadge.setWordWrap(True)
        self.lblBadge.setObjectName("lblBadge")
        self.btnCritical = QtWidgets.QPushButton(Dashboard)
        self.btnCritical.setGeometry(QtCore.QRect(1340, 760, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnCritical.setFont(font)
        self.btnCritical.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnCritical.setObjectName("btnCritical")
        self.btnCompare = QtWidgets.QPushButton(Dashboard)
        self.btnCompare.setGeometry(QtCore.QRect(1340, 820, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnCompare.setFont(font)
        self.btnCompare.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnCompare.setObjectName("btnCompare")
        self.frame_5 = QtWidgets.QFrame(Dashboard)
        self.frame_5.setGeometry(QtCore.QRect(20, 750, 1211, 121))
        self.frame_5.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    background: rgba(0,0,0,128);\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.lblPerformance = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerformance.sizePolicy().hasHeightForWidth())
        self.lblPerformance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblPerformance.setFont(font)
        self.lblPerformance.setStyleSheet("background: transparent;\n"
"color: white;")
        self.lblPerformance.setText("")
        self.lblPerformance.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPerformance.setWordWrap(True)
        self.lblPerformance.setObjectName("lblPerformance")
        self.gridLayout.addWidget(self.lblPerformance, 0, 0, 1, 1)
        self.lsExpProducts = QtWidgets.QListWidget(Dashboard)
        self.lsExpProducts.setGeometry(QtCore.QRect(1230, 60, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lsExpProducts.setFont(font)
        self.lsExpProducts.setStyleSheet("border: 0px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgba(56,92,108,196);\n"
"color: white;")
        self.lsExpProducts.setObjectName("lsExpProducts")

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Form"))
        self.label_2.setText(_translate("Dashboard", "Dashboard"))
        self.label_3.setText(_translate("Dashboard", "This Month\'s Performance"))
        self.label_4.setText(_translate("Dashboard", "Product of the Month"))
        self.btnSales.setText(_translate("Dashboard", "Sales"))
        self.btnInventory.setText(_translate("Dashboard", "Inventory"))
        self.btnPOS.setText(_translate("Dashboard", "POS"))
        self.btnDashboard.setText(_translate("Dashboard", "EconoMystique"))
        self.lblBadge.setText(_translate("Dashboard", "2"))
        self.btnCritical.setText(_translate("Dashboard", "Critical Items"))
        self.btnCompare.setText(_translate("Dashboard", "Compare"))
