# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\inventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inventoryManagement(object):
    def setupUi(self, inventoryManagement):
        inventoryManagement.setObjectName("inventoryManagement")
        inventoryManagement.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        inventoryManagement.setWindowIcon(icon)
        inventoryManagement.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;\n"
"")
        self.frame = QtWidgets.QFrame(inventoryManagement)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(660, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(750, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(570, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(480, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnDashboard = QtWidgets.QPushButton(self.frame)
        self.btnDashboard.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon2)
        self.btnDashboard.setObjectName("btnDashboard")
        self.InventoryStatus = QtWidgets.QLabel(inventoryManagement)
        self.InventoryStatus.setGeometry(QtCore.QRect(9, 50, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.InventoryStatus.setFont(font)
        self.InventoryStatus.setStyleSheet("background-color: transparent;")
        self.InventoryStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.InventoryStatus.setObjectName("InventoryStatus")
        self.tabWidget = QtWidgets.QTabWidget(inventoryManagement)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 781, 491))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabIngredients = QtWidgets.QWidget()
        self.tabIngredients.setObjectName("tabIngredients")
        self.tabIngredientTable = QtWidgets.QTableWidget(self.tabIngredients)
        self.tabIngredientTable.setGeometry(QtCore.QRect(0, 0, 781, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabIngredientTable.sizePolicy().hasHeightForWidth())
        self.tabIngredientTable.setSizePolicy(sizePolicy)
        self.tabIngredientTable.setMaximumSize(QtCore.QSize(1920, 1080))
        self.tabIngredientTable.setStyleSheet("background: #ffffff")
        self.tabIngredientTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabIngredientTable.setObjectName("tabIngredientTable")
        self.tabIngredientTable.setColumnCount(0)
        self.tabIngredientTable.setRowCount(0)
        self.btnRestock = QtWidgets.QPushButton(self.tabIngredients)
        self.btnRestock.setGeometry(QtCore.QRect(330, 400, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRestock.setFont(font)
        self.btnRestock.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/restock_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRestock.setIcon(icon3)
        self.btnRestock.setObjectName("btnRestock")
        self.tabWidget.addTab(self.tabIngredients, "")
        self.tabProducts = QtWidgets.QWidget()
        self.tabProducts.setObjectName("tabProducts")
        self.tabProductTable = QtWidgets.QTableWidget(self.tabProducts)
        self.tabProductTable.setGeometry(QtCore.QRect(0, 0, 781, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabProductTable.sizePolicy().hasHeightForWidth())
        self.tabProductTable.setSizePolicy(sizePolicy)
        self.tabProductTable.setMaximumSize(QtCore.QSize(1920, 1080))
        self.tabProductTable.setStyleSheet("background: #ffffff")
        self.tabProductTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabProductTable.setObjectName("tabProductTable")
        self.tabProductTable.setColumnCount(0)
        self.tabProductTable.setRowCount(0)
        self.btnAddProduct = QtWidgets.QPushButton(self.tabProducts)
        self.btnAddProduct.setGeometry(QtCore.QRect(320, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAddProduct.setFont(font)
        self.btnAddProduct.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAddProduct.setIcon(icon3)
        self.btnAddProduct.setObjectName("btnAddProduct")
        self.tabWidget.addTab(self.tabProducts, "")

        self.retranslateUi(inventoryManagement)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(inventoryManagement)

    def retranslateUi(self, inventoryManagement):
        _translate = QtCore.QCoreApplication.translate
        inventoryManagement.setWindowTitle(_translate("inventoryManagement", "EconoMystique"))
        self.btnPOS.setText(_translate("inventoryManagement", "POS"))
        self.btnSales.setText(_translate("inventoryManagement", "Sales"))
        self.btnInventory.setText(_translate("inventoryManagement", "Inventory"))
        self.btnDashboard.setText(_translate("inventoryManagement", "EconoMystique"))
        self.InventoryStatus.setText(_translate("inventoryManagement", "Inventory Status"))
        self.btnRestock.setText(_translate("inventoryManagement", " Restock"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIngredients), _translate("inventoryManagement", "Ingredients"))
        self.btnAddProduct.setText(_translate("inventoryManagement", "Add Product"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProducts), _translate("inventoryManagement", "Products"))
