# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\inventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inventoryManagement(object):
    def setupUi(self, inventoryManagement):
        inventoryManagement.setObjectName("inventoryManagement")
        inventoryManagement.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        inventoryManagement.setWindowIcon(icon)
        inventoryManagement.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;\n"
"")
        self.frame = QtWidgets.QFrame(inventoryManagement)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(660, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(750, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(570, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(480, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.tabWidget = QtWidgets.QTabWidget(inventoryManagement)
        self.tabWidget.setGeometry(QtCore.QRect(10, 130, 781, 381))
        self.tabWidget.setStyleSheet("background-color: white;\n"
"color: black;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab1Table = QtWidgets.QTableWidget(self.tab)
        self.tab1Table.setGeometry(QtCore.QRect(0, 0, 771, 351))
        self.tab1Table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tab1Table.setObjectName("tab1Table")
        self.tab1Table.setColumnCount(0)
        self.tab1Table.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.InventoryStatus = QtWidgets.QLabel(inventoryManagement)
        self.InventoryStatus.setGeometry(QtCore.QRect(9, 50, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.InventoryStatus.setFont(font)
        self.InventoryStatus.setStyleSheet("background-color: transparent;")
        self.InventoryStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.InventoryStatus.setObjectName("InventoryStatus")
        self.frame_2 = QtWidgets.QFrame(inventoryManagement)
        self.frame_2.setGeometry(QtCore.QRect(160, 520, 471, 61))
        self.frame_2.setStyleSheet("background: #f4f4ec;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnEdit = QtWidgets.QPushButton(self.frame_2)
        self.btnEdit.setGeometry(QtCore.QRect(240, 20, 101, 31))
        self.btnEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/editPfp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEdit.setIcon(icon2)
        self.btnEdit.setFlat(True)
        self.btnEdit.setObjectName("btnEdit")
        self.btnSave = QtWidgets.QPushButton(self.frame_2)
        self.btnSave.setGeometry(QtCore.QRect(350, 20, 111, 31))
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/saveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon3)
        self.btnSave.setFlat(True)
        self.btnSave.setObjectName("btnSave")
        self.btnAddItem = QtWidgets.QPushButton(self.frame_2)
        self.btnAddItem.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.btnAddItem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/plusIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddItem.setIcon(icon4)
        self.btnAddItem.setFlat(True)
        self.btnAddItem.setObjectName("btnAddItem")
        self.btnRemoveItem = QtWidgets.QPushButton(self.frame_2)
        self.btnRemoveItem.setGeometry(QtCore.QRect(120, 20, 121, 31))
        self.btnRemoveItem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRemoveItem.setIcon(icon4)
        self.btnRemoveItem.setFlat(True)
        self.btnRemoveItem.setObjectName("btnRemoveItem")

        self.retranslateUi(inventoryManagement)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(inventoryManagement)

    def retranslateUi(self, inventoryManagement):
        _translate = QtCore.QCoreApplication.translate
        inventoryManagement.setWindowTitle(_translate("inventoryManagement", "EconoMystique"))
        self.titleLabel.setText(_translate("inventoryManagement", "EconoMystique"))
        self.btnPOS.setText(_translate("inventoryManagement", "POS"))
        self.btnSales.setText(_translate("inventoryManagement", "Sales"))
        self.btnInventory.setText(_translate("inventoryManagement", "Inventory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("inventoryManagement", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("inventoryManagement", "Tab 2"))
        self.InventoryStatus.setText(_translate("inventoryManagement", "Inventory Status"))
        self.btnEdit.setText(_translate("inventoryManagement", "Edit Items"))
        self.btnSave.setText(_translate("inventoryManagement", "Save Changes"))
        self.btnAddItem.setText(_translate("inventoryManagement", "Add Item"))
        self.btnRemoveItem.setText(_translate("inventoryManagement", "Remove Item"))
