# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Patricia\Economystique2\landingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_landingPage(object):
    def setupUi(self, landingPage):
        landingPage.setObjectName("landingPage")
        landingPage.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/econoLogo2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        landingPage.setWindowIcon(icon)
        landingPage.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;")
        self.centralwidget = QtWidgets.QWidget(landingPage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setGeometry(QtCore.QRect(310, 190, 161, 321))
        self.verticalWidget_2.setStyleSheet("QWidget#verticalWidget_2{\n"
"background: transparent;\n"
"}")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dueInButton = QtWidgets.QPushButton(self.verticalWidget_2)
        self.dueInButton.setMinimumSize(QtCore.QSize(0, 50))
        self.dueInButton.setStyleSheet("QPushButton{\n"
"    background-color: #86ada0;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"    border: 2px solid #86ada0;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.dueInButton.setObjectName("dueInButton")
        self.verticalLayout_2.addWidget(self.dueInButton)
        self.onHandButton = QtWidgets.QPushButton(self.verticalWidget_2)
        self.onHandButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.onHandButton.setFont(font)
        self.onHandButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.onHandButton.setStyleSheet("QPushButton {\n"
"    background-color: #53786d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"    border: 2px solid #53786d;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.onHandButton.setDefault(False)
        self.onHandButton.setFlat(False)
        self.onHandButton.setObjectName("onHandButton")
        self.verticalLayout_2.addWidget(self.onHandButton)
        self.owedButton = QtWidgets.QPushButton(self.verticalWidget_2)
        self.owedButton.setMinimumSize(QtCore.QSize(0, 50))
        self.owedButton.setStyleSheet("QPushButton{\n"
"    background-color: #4e655e;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"    border: 2px solid #4e655e;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #4e655e;\n"
"}")
        self.owedButton.setObjectName("owedButton")
        self.verticalLayout_2.addWidget(self.owedButton)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.btnCalendar = QtWidgets.QPushButton(self.frame)
        self.btnCalendar.setGeometry(QtCore.QRect(660, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCalendar.setFont(font)
        self.btnCalendar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalendar.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnCalendar.setObjectName("btnCalendar")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(750, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/pfBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(570, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(480, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.recommendationButton = QtWidgets.QPushButton(self.centralwidget)
        self.recommendationButton.setGeometry(QtCore.QRect(550, 460, 201, 51))
        self.recommendationButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recommendationButton.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"    border: 2px solid #365b6d;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.recommendationButton.setDefault(False)
        self.recommendationButton.setObjectName("recommendationButton")
        self.Assessment = QtWidgets.QLabel(self.centralwidget)
        self.Assessment.setGeometry(QtCore.QRect(500, 127, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Assessment.setFont(font)
        self.Assessment.setStyleSheet("background-color: transparent;")
        self.Assessment.setAlignment(QtCore.Qt.AlignCenter)
        self.Assessment.setObjectName("Assessment")
        self.Summary = QtWidgets.QLabel(self.centralwidget)
        self.Summary.setGeometry(QtCore.QRect(10, 127, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Summary.setFont(font)
        self.Summary.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Summary.setStyleSheet("background-color: transparent;")
        self.Summary.setAlignment(QtCore.Qt.AlignCenter)
        self.Summary.setObjectName("Summary")
        self.assessmentListView = QtWidgets.QListView(self.centralwidget)
        self.assessmentListView.setGeometry(QtCore.QRect(500, 190, 291, 241))
        self.assessmentListView.setStyleSheet("background-color: transparent;\n"
"color: black;")
        self.assessmentListView.setObjectName("assessmentListView")
        self.summaryListView = QtWidgets.QListView(self.centralwidget)
        self.summaryListView.setGeometry(QtCore.QRect(10, 190, 279, 319))
        self.summaryListView.setStyleSheet("background-color: transparent;\n"
"color: black;")
        self.summaryListView.setObjectName("summaryListView")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 801, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(290, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InventoryStatus = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.InventoryStatus.setFont(font)
        self.InventoryStatus.setStyleSheet("background-color: transparent;")
        self.InventoryStatus.setObjectName("InventoryStatus")
        self.verticalLayout.addWidget(self.InventoryStatus)
        landingPage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(landingPage)
        self.statusbar.setObjectName("statusbar")
        landingPage.setStatusBar(self.statusbar)

        self.retranslateUi(landingPage)
        QtCore.QMetaObject.connectSlotsByName(landingPage)

    def retranslateUi(self, landingPage):
        _translate = QtCore.QCoreApplication.translate
        landingPage.setWindowTitle(_translate("landingPage", "EconoMystique"))
        self.dueInButton.setText(_translate("landingPage", "DUE-IN STOCKS"))
        self.onHandButton.setText(_translate("landingPage", "ON-HAND STOCKS"))
        self.owedButton.setText(_translate("landingPage", "OWED STOCKS"))
        self.titleLabel.setText(_translate("landingPage", "EconoMystique"))
        self.btnCalendar.setText(_translate("landingPage", "Calendar"))
        self.btnSales.setText(_translate("landingPage", "Sales"))
        self.btnInventory.setText(_translate("landingPage", "Inventory"))
        self.recommendationButton.setText(_translate("landingPage", "REQUEST RECOMMENDATION"))
        self.Assessment.setText(_translate("landingPage", "ASSESSMENT"))
        self.Summary.setText(_translate("landingPage", "SUMMARY"))
        self.InventoryStatus.setText(_translate("landingPage", "Inventory Status"))
