from PyQt5.QtWidgets import QApplication, QMainWindow
from salesForecast import SalesForecastWindow


class LandingPage(QMainWindow):
    def __init__(self):
        super(LandingPage, self).__init__()
        
        # Set up your landing page UI logic here or load from the autogenerated file
        from landingPage_ui import Ui_MainWindow
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Connect button
        self.ui.recommendationButton.clicked.connect(self.open_forecast)

    def open_forecast(self):
        self.sales_forecast_window = SalesForecastWindow()
        self.sales_forecast_window.show()
        self.close()