# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Patricia\Economystique2\mainInventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainInventory(object):
    def setupUi(self, mainInventory):
        mainInventory.setObjectName("mainInventory")
        mainInventory.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/econologo.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        mainInventory.setWindowIcon(icon)
        mainInventory.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;")
        self.assessmentListView = QtWidgets.QListView(mainInventory)
        self.assessmentListView.setGeometry(QtCore.QRect(10, 450, 781, 81))
        self.assessmentListView.setStyleSheet("background-color: transparent;\n"
"color: black;")
        self.assessmentListView.setObjectName("assessmentListView")
        self.frame = QtWidgets.QFrame(mainInventory)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.btnCalendar = QtWidgets.QPushButton(self.frame)
        self.btnCalendar.setGeometry(QtCore.QRect(660, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCalendar.setFont(font)
        self.btnCalendar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalendar.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnCalendar.setObjectName("btnCalendar")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(750, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Patricia\\Economystique2\\img/pfBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(570, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(480, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.productsListView = QtWidgets.QListView(mainInventory)
        self.productsListView.setGeometry(QtCore.QRect(10, 90, 781, 261))
        self.productsListView.setStyleSheet("background-color: transparent;\n"
"color: black;")
        self.productsListView.setObjectName("productsListView")
        self.recommendationButton = QtWidgets.QPushButton(mainInventory)
        self.recommendationButton.setGeometry(QtCore.QRect(310, 540, 201, 51))
        self.recommendationButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recommendationButton.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"    border: 2px solid #365b6d;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.recommendationButton.setDefault(False)
        self.recommendationButton.setObjectName("recommendationButton")
        self.goToInventory = QtWidgets.QPushButton(mainInventory)
        self.goToInventory.setGeometry(QtCore.QRect(650, 360, 139, 50))
        self.goToInventory.setMinimumSize(QtCore.QSize(0, 50))
        self.goToInventory.setStyleSheet("QPushButton{\n"
"    background-color: #86ada0;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"    border: 2px solid #86ada0;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.goToInventory.setObjectName("goToInventory")
        self.Summary = QtWidgets.QLabel(mainInventory)
        self.Summary.setGeometry(QtCore.QRect(360, 50, 99, 49))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Summary.setFont(font)
        self.Summary.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Summary.setStyleSheet("background-color: transparent;")
        self.Summary.setAlignment(QtCore.Qt.AlignCenter)
        self.Summary.setObjectName("Summary")
        self.Assessment = QtWidgets.QLabel(mainInventory)
        self.Assessment.setGeometry(QtCore.QRect(350, 410, 118, 49))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Assessment.setFont(font)
        self.Assessment.setStyleSheet("background-color: transparent;")
        self.Assessment.setAlignment(QtCore.Qt.AlignCenter)
        self.Assessment.setObjectName("Assessment")

        self.retranslateUi(mainInventory)
        QtCore.QMetaObject.connectSlotsByName(mainInventory)

    def retranslateUi(self, mainInventory):
        _translate = QtCore.QCoreApplication.translate
        mainInventory.setWindowTitle(_translate("mainInventory", "EconoMystique"))
        self.titleLabel.setText(_translate("mainInventory", "EconoMystique"))
        self.btnCalendar.setText(_translate("mainInventory", "Calendar"))
        self.btnSales.setText(_translate("mainInventory", "Sales"))
        self.btnInventory.setText(_translate("mainInventory", "Inventory"))
        self.recommendationButton.setText(_translate("mainInventory", "REQUEST RECOMMENDATION"))
        self.goToInventory.setText(_translate("mainInventory", "Go to INVENTORY >>"))
        self.Summary.setText(_translate("mainInventory", "PRODUCTS"))
        self.Assessment.setText(_translate("mainInventory", "ASSESSMENT"))
