# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\restock.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Restock(object):
    def setupUi(self, Restock):
        Restock.setObjectName("Restock")
        Restock.resize(799, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Restock.setWindowIcon(icon)
        Restock.setStyleSheet("background-color: #f4f4ec;")
        self.btnConfirm = QtWidgets.QPushButton(Restock)
        self.btnConfirm.setGeometry(QtCore.QRect(300, 560, 121, 28))
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnCancel = QtWidgets.QPushButton(Restock)
        self.btnCancel.setGeometry(QtCore.QRect(430, 560, 131, 28))
        self.btnCancel.setObjectName("btnCancel")
        self.frame = QtWidgets.QFrame(Restock)
        self.frame.setGeometry(QtCore.QRect(10, 140, 411, 331))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 51, 111, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.loParam = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.loParam.setContentsMargins(0, 0, 0, 0)
        self.loParam.setObjectName("loParam")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("color: White;")
        self.label.setObjectName("label")
        self.loParam.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setStyleSheet("color: White;")
        self.label_2.setObjectName("label_2")
        self.loParam.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("color: White;")
        self.label_3.setObjectName("label_3")
        self.loParam.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("color: White;")
        self.label_4.setObjectName("label_4")
        self.loParam.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setStyleSheet("color: White;")
        self.label_7.setObjectName("label_7")
        self.loParam.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setStyleSheet("color: White;")
        self.label_6.setObjectName("label_6")
        self.loParam.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setStyleSheet("color: White;")
        self.label_5.setObjectName("label_5")
        self.loParam.addWidget(self.label_5)
        self.teDueIn = QtWidgets.QTextEdit(self.frame)
        self.teDueIn.setGeometry(QtCore.QRect(130, 280, 256, 31))
        self.teDueIn.setStyleSheet("background: #ffffff")
        self.teDueIn.setFrameShape(QtWidgets.QFrame.Panel)
        self.teDueIn.setTabChangesFocus(True)
        self.teDueIn.setObjectName("teDueIn")
        self.teInvID = QtWidgets.QTextEdit(self.frame)
        self.teInvID.setGeometry(QtCore.QRect(130, 52, 256, 31))
        self.teInvID.setStyleSheet("background: #ffffff")
        self.teInvID.setFrameShape(QtWidgets.QFrame.Panel)
        self.teInvID.setTabChangesFocus(True)
        self.teInvID.setObjectName("teInvID")
        self.teOwed = QtWidgets.QTextEdit(self.frame)
        self.teOwed.setGeometry(QtCore.QRect(130, 242, 256, 31))
        self.teOwed.setStyleSheet("background: #ffffff")
        self.teOwed.setFrameShape(QtWidgets.QFrame.Panel)
        self.teOwed.setTabChangesFocus(True)
        self.teOwed.setObjectName("teOwed")
        self.teBrand = QtWidgets.QTextEdit(self.frame)
        self.teBrand.setGeometry(QtCore.QRect(130, 128, 256, 31))
        self.teBrand.setStyleSheet("background: #ffffff")
        self.teBrand.setFrameShape(QtWidgets.QFrame.Panel)
        self.teBrand.setTabChangesFocus(True)
        self.teBrand.setObjectName("teBrand")
        self.teOnHand = QtWidgets.QTextEdit(self.frame)
        self.teOnHand.setGeometry(QtCore.QRect(130, 204, 256, 31))
        self.teOnHand.setStyleSheet("background: #ffffff")
        self.teOnHand.setFrameShape(QtWidgets.QFrame.Panel)
        self.teOnHand.setTabChangesFocus(True)
        self.teOnHand.setObjectName("teOnHand")
        self.teDescription = QtWidgets.QTextEdit(self.frame)
        self.teDescription.setGeometry(QtCore.QRect(130, 90, 256, 31))
        self.teDescription.setStyleSheet("background: #ffffff")
        self.teDescription.setFrameShape(QtWidgets.QFrame.Panel)
        self.teDescription.setTabChangesFocus(True)
        self.teDescription.setObjectName("teDescription")
        self.teUnit = QtWidgets.QTextEdit(self.frame)
        self.teUnit.setGeometry(QtCore.QRect(130, 166, 256, 31))
        self.teUnit.setStyleSheet("background: #ffffff")
        self.teUnit.setFrameShape(QtWidgets.QFrame.Panel)
        self.teUnit.setTabChangesFocus(True)
        self.teUnit.setObjectName("teUnit")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(14, 9, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:White;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Restock)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 781, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_2 = QtWidgets.QFrame(Restock)
        self.frame_2.setGeometry(QtCore.QRect(430, 140, 361, 331))
        self.frame_2.setStyleSheet("background: #365b6d;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lsRestock = QtWidgets.QListView(self.frame_2)
        self.lsRestock.setGeometry(QtCore.QRect(20, 50, 321, 261))
        self.lsRestock.setAutoFillBackground(False)
        self.lsRestock.setStyleSheet("background: White;")
        self.lsRestock.setObjectName("lsRestock")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:White;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btnAdd = QtWidgets.QPushButton(Restock)
        self.btnAdd.setGeometry(QtCore.QRect(140, 490, 131, 28))
        self.btnAdd.setObjectName("btnAdd")
        self.btnRemove = QtWidgets.QPushButton(Restock)
        self.btnRemove.setGeometry(QtCore.QRect(560, 490, 131, 28))
        self.btnRemove.setObjectName("btnRemove")

        self.retranslateUi(Restock)
        QtCore.QMetaObject.connectSlotsByName(Restock)

    def retranslateUi(self, Restock):
        _translate = QtCore.QCoreApplication.translate
        Restock.setWindowTitle(_translate("Restock", "Restock Inventory"))
        self.btnConfirm.setText(_translate("Restock", "✔️ Confirm"))
        self.btnCancel.setText(_translate("Restock", "❌ Cancel"))
        self.label.setText(_translate("Restock", "Inventory ID"))
        self.label_2.setText(_translate("Restock", "Description"))
        self.label_3.setText(_translate("Restock", "Brand"))
        self.label_4.setText(_translate("Restock", "Unit"))
        self.label_7.setText(_translate("Restock", "On-Hand Stocks"))
        self.label_6.setText(_translate("Restock", "Owed Stocks"))
        self.label_5.setText(_translate("Restock", "Due-In Stocks"))
        self.teDueIn.setHtml(_translate("Restock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teInvID.setHtml(_translate("Restock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teOwed.setHtml(_translate("Restock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teBrand.setHtml(_translate("Restock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teOnHand.setHtml(_translate("Restock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teDescription.setHtml(_translate("Restock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teUnit.setHtml(_translate("Restock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_8.setText(_translate("Restock", "Add Item"))
        self.label_9.setText(_translate("Restock", "Restock Inventory"))
        self.label_10.setText(_translate("Restock", "Restock List"))
        self.btnAdd.setText(_translate("Restock", "Add"))
        self.btnRemove.setText(_translate("Restock", "Remove"))
