# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\restock.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Restock(object):
    def setupUi(self, Restock):
        Restock.setObjectName("Restock")
        Restock.resize(667, 397)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Restock.setWindowIcon(icon)
        Restock.setStyleSheet("background-color: #f4f4ec;")
        self.btnConfirm = QtWidgets.QPushButton(Restock)
        self.btnConfirm.setGeometry(QtCore.QRect(200, 350, 121, 28))
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnCancel = QtWidgets.QPushButton(Restock)
        self.btnCancel.setGeometry(QtCore.QRect(350, 350, 121, 28))
        self.btnCancel.setObjectName("btnCancel")
        self.label_9 = QtWidgets.QLabel(Restock)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 651, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.btnRemove = QtWidgets.QPushButton(Restock)
        self.btnRemove.setGeometry(QtCore.QRect(520, 260, 131, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/deleteIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon1)
        self.btnRemove.setObjectName("btnRemove")
        self.btnAddNew = QtWidgets.QPushButton(Restock)
        self.btnAddNew.setGeometry(QtCore.QRect(520, 190, 131, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/plusIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddNew.setIcon(icon2)
        self.btnAddNew.setObjectName("btnAddNew")
        self.tabRestockTable = QtWidgets.QTableWidget(Restock)
        self.tabRestockTable.setGeometry(QtCore.QRect(10, 80, 501, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabRestockTable.sizePolicy().hasHeightForWidth())
        self.tabRestockTable.setSizePolicy(sizePolicy)
        self.tabRestockTable.setMaximumSize(QtCore.QSize(771, 351))
        self.tabRestockTable.setStyleSheet("background: #ffffff")
        self.tabRestockTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabRestockTable.setObjectName("tabRestockTable")
        self.tabRestockTable.setColumnCount(0)
        self.tabRestockTable.setRowCount(0)
        self.btnAdd = QtWidgets.QPushButton(Restock)
        self.btnAdd.setGeometry(QtCore.QRect(520, 120, 131, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/addIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon3)
        self.btnAdd.setObjectName("btnAdd")

        self.retranslateUi(Restock)
        QtCore.QMetaObject.connectSlotsByName(Restock)

    def retranslateUi(self, Restock):
        _translate = QtCore.QCoreApplication.translate
        Restock.setWindowTitle(_translate("Restock", "Restock Inventory"))
        self.btnConfirm.setText(_translate("Restock", "✔️ Confirm"))
        self.btnCancel.setText(_translate("Restock", "❌ Cancel"))
        self.label_9.setText(_translate("Restock", "Restock Inventory"))
        self.btnRemove.setText(_translate("Restock", "Remove"))
        self.btnAddNew.setText(_translate("Restock", "Add New Item"))
        self.btnAdd.setText(_translate("Restock", "Add Existing Item"))
