# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\sales.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sales(object):
    def setupUi(self, Sales):
        Sales.setObjectName("Sales")
        Sales.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\../.designer/backup/img/econoLogo2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Sales.setWindowIcon(icon)
        Sales.setStyleSheet("background: #f4f4ec;\n"
"color: black;\n"
"")
        self.frame = QtWidgets.QFrame(Sales)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1601, 41))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(1370, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(1280, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(1460, 0, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(1550, 0, 51, 41))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(40, 40))
        self.btnAccount.setObjectName("btnAccount")
        self.btnDashboard = QtWidgets.QPushButton(self.frame)
        self.btnDashboard.setGeometry(QtCore.QRect(0, 0, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon2)
        self.btnDashboard.setObjectName("btnDashboard")
        self.SalesRecords = QtWidgets.QLabel(Sales)
        self.SalesRecords.setGeometry(QtCore.QRect(9, 47, 1581, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.SalesRecords.setFont(font)
        self.SalesRecords.setAlignment(QtCore.Qt.AlignCenter)
        self.SalesRecords.setObjectName("SalesRecords")
        self.QTabWidget = QtWidgets.QTabWidget(Sales)
        self.QTabWidget.setGeometry(QtCore.QRect(20, 100, 1561, 771))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.QTabWidget.setFont(font)
        self.QTabWidget.setObjectName("QTabWidget")
        self.tabToday = QtWidgets.QWidget()
        self.tabToday.setObjectName("tabToday")
        self.productTable = QtWidgets.QTableWidget(self.tabToday)
        self.productTable.setGeometry(QtCore.QRect(0, 0, 1561, 611))
        self.productTable.setStyleSheet("background: #ffffff")
        self.productTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.productTable.setObjectName("productTable")
        self.productTable.setColumnCount(0)
        self.productTable.setRowCount(0)
        self.lblTotal = QtWidgets.QLabel(self.tabToday)
        self.lblTotal.setGeometry(QtCore.QRect(110, 650, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblTotal.setFont(font)
        self.lblTotal.setStyleSheet("background: white;\n"
"")
        self.lblTotal.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTotal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblTotal.setText("")
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setObjectName("lblTotal")
        self.label = QtWidgets.QLabel(self.tabToday)
        self.label.setGeometry(QtCore.QRect(10, 650, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnAssessment = QtWidgets.QPushButton(self.tabToday)
        self.btnAssessment.setGeometry(QtCore.QRect(920, 650, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAssessment.setFont(font)
        self.btnAssessment.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAssessment.setObjectName("btnAssessment")
        self.forecastButton = QtWidgets.QPushButton(self.tabToday)
        self.forecastButton.setGeometry(QtCore.QRect(1240, 650, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.forecastButton.setFont(font)
        self.forecastButton.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.forecastButton.setIcon(icon2)
        self.forecastButton.setIconSize(QtCore.QSize(15, 40))
        self.forecastButton.setObjectName("forecastButton")
        self.QTabWidget.addTab(self.tabToday, "")
        self.tabMonthly = QtWidgets.QWidget()
        self.tabMonthly.setObjectName("tabMonthly")
        self.cbYear_2 = QtWidgets.QComboBox(self.tabMonthly)
        self.cbYear_2.setGeometry(QtCore.QRect(140, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbYear_2.setFont(font)
        self.cbYear_2.setStyleSheet("background: white;")
        self.cbYear_2.setObjectName("cbYear_2")
        self.label_3 = QtWidgets.QLabel(self.tabMonthly)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabMonthly)
        self.label_4.setGeometry(QtCore.QRect(10, 650, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btnAssessment_2 = QtWidgets.QPushButton(self.tabMonthly)
        self.btnAssessment_2.setGeometry(QtCore.QRect(920, 650, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAssessment_2.setFont(font)
        self.btnAssessment_2.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAssessment_2.setObjectName("btnAssessment_2")
        self.forecastButton_2 = QtWidgets.QPushButton(self.tabMonthly)
        self.forecastButton_2.setGeometry(QtCore.QRect(1240, 650, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.forecastButton_2.setFont(font)
        self.forecastButton_2.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.forecastButton_2.setIcon(icon2)
        self.forecastButton_2.setIconSize(QtCore.QSize(15, 40))
        self.forecastButton_2.setObjectName("forecastButton_2")
        self.lblTotal_2 = QtWidgets.QLabel(self.tabMonthly)
        self.lblTotal_2.setGeometry(QtCore.QRect(110, 650, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblTotal_2.setFont(font)
        self.lblTotal_2.setStyleSheet("background: white;\n"
"")
        self.lblTotal_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTotal_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblTotal_2.setText("")
        self.lblTotal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal_2.setObjectName("lblTotal_2")
        self.productTable_2 = QtWidgets.QTableWidget(self.tabMonthly)
        self.productTable_2.setGeometry(QtCore.QRect(0, 90, 1561, 521))
        self.productTable_2.setStyleSheet("background: #ffffff")
        self.productTable_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.productTable_2.setObjectName("productTable_2")
        self.productTable_2.setColumnCount(0)
        self.productTable_2.setRowCount(0)
        self.QTabWidget.addTab(self.tabMonthly, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.cbYear_3 = QtWidgets.QComboBox(self.tab)
        self.cbYear_3.setGeometry(QtCore.QRect(140, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbYear_3.setFont(font)
        self.cbYear_3.setStyleSheet("background: white;")
        self.cbYear_3.setObjectName("cbYear_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.forecastButton_3 = QtWidgets.QPushButton(self.tab)
        self.forecastButton_3.setGeometry(QtCore.QRect(1240, 650, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.forecastButton_3.setFont(font)
        self.forecastButton_3.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.forecastButton_3.setIcon(icon2)
        self.forecastButton_3.setIconSize(QtCore.QSize(15, 40))
        self.forecastButton_3.setObjectName("forecastButton_3")
        self.productTable_3 = QtWidgets.QTableWidget(self.tab)
        self.productTable_3.setGeometry(QtCore.QRect(0, 90, 1561, 521))
        self.productTable_3.setStyleSheet("background: #ffffff")
        self.productTable_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.productTable_3.setObjectName("productTable_3")
        self.productTable_3.setColumnCount(0)
        self.productTable_3.setRowCount(0)
        self.btnAssessment_3 = QtWidgets.QPushButton(self.tab)
        self.btnAssessment_3.setGeometry(QtCore.QRect(920, 650, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAssessment_3.setFont(font)
        self.btnAssessment_3.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAssessment_3.setObjectName("btnAssessment_3")
        self.lblTotal_3 = QtWidgets.QLabel(self.tab)
        self.lblTotal_3.setGeometry(QtCore.QRect(110, 650, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblTotal_3.setFont(font)
        self.lblTotal_3.setStyleSheet("background: white;\n"
"")
        self.lblTotal_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTotal_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblTotal_3.setText("")
        self.lblTotal_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal_3.setObjectName("lblTotal_3")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 650, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.QTabWidget.addTab(self.tab, "")

        self.retranslateUi(Sales)
        self.QTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Sales)

    def retranslateUi(self, Sales):
        _translate = QtCore.QCoreApplication.translate
        Sales.setWindowTitle(_translate("Sales", "EconoMystique"))
        self.btnSales.setText(_translate("Sales", "Sales"))
        self.btnInventory.setText(_translate("Sales", "Inventory"))
        self.btnPOS.setText(_translate("Sales", "POS"))
        self.btnDashboard.setText(_translate("Sales", "EconoMystique"))
        self.SalesRecords.setText(_translate("Sales", "Sales"))
        self.label.setText(_translate("Sales", "Total"))
        self.btnAssessment.setText(_translate("Sales", "See Assessment"))
        self.forecastButton.setText(_translate("Sales", "Generate Forecast"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.tabToday), _translate("Sales", "Today"))
        self.label_3.setText(_translate("Sales", "Month:"))
        self.label_4.setText(_translate("Sales", "Total"))
        self.btnAssessment_2.setText(_translate("Sales", "See Assessment"))
        self.forecastButton_2.setText(_translate("Sales", "Generate Forecast"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.tabMonthly), _translate("Sales", "Monthly"))
        self.label_5.setText(_translate("Sales", "Year:"))
        self.forecastButton_3.setText(_translate("Sales", "Generate Forecast"))
        self.btnAssessment_3.setText(_translate("Sales", "See Assessment"))
        self.label_6.setText(_translate("Sales", "Total"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.tab), _translate("Sales", "Yearly"))
